[Settings]
# https://docs.netlify.com/configure-builds/file-based-configuration/

##################################################
# build settings
[build]
#   base = "/"

  command = "npm run build"
  publish = "dist/"

# build environment
[build.environment]
  HUGO_VERSION = "0.70.0"
  NODE_VERSION = "14.2.0"

# build processing
[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

# redirects
##################################################
[[redirects]]
  from = "/src"
  status = 301
  to = "https://gitlab.com/u29dc/set/css"

[[redirects]]
  from = "/css"
  status = 301
  to = "https://cdn.jsdelivr.net/npm/@u29dc/set@1.5.0/dist/css/main.min.css"

# headers
##################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = """
        base-uri 'self';
        default-src 'none';
        font-src 'self' cdn.jsdelivr.net;
        form-action 'self';
        frame-ancestors 'none';
        frame-src 'self';
        img-src 'self' data:;
        manifest-src 'self';
        media-src 'self';
        object-src 'none';
        script-src 'self' cdn.jsdelivr.net;
        style-src 'self' cdn.jsdelivr.net;
        upgrade-insecure-requests;
    """
    Expect-CT = "max-age=86400; report-uri='https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct'"
    Feature-Policy = """
        accelerometer 'self';
        ambient-light-sensor 'self';
        autoplay 'self';
        camera 'self';
        document-domain 'self';
        encrypted-media 'self';
        fullscreen 'self';
        geolocation 'self';
        gyroscope 'self';
        magnetometer 'self';
        microphone 'self';
        midi 'self';
        payment 'self';
        picture-in-picture 'self';
        speaker 'self';
        sync-xhr 'self';
        usb 'self';
        vr / xr 'self';
    """
    Referrer-Policy = "strict-origin"
    Strict-Transport-Security = "max-age=31557600; includesubdomains; preload"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
